version: '3.2'
services:
  nest-project:
    environment:
     - JWT_SECRET=secret
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    network_mode: 'host'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: always
    network_mode: 'host'

